from django.urls import path
from hubspot.views import (
    EventHubSpotCallbackView,
    EventHubSpotConnectView,
    EventHubSpotDisconnectView,
    EventHubSpotFieldMappingView,
    EventHubSpotSettingsView,
    EventHubSpotLogView,
    EventHubSpotSyncMappingView,
    SyncProblemsView,
    RetrySyncView,
    RetryAllFailedView,
    SyncRetryBulkView,
    DismissSyncView,
)

urlpatterns = [
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/",
        EventHubSpotSettingsView.as_view(),
        name="hubspot",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/connect/",
        EventHubSpotConnectView.as_view(),
        name="connect",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/disconnect/",
        EventHubSpotDisconnectView.as_view(),
        name="disconnect",
    ),
    path(
        "control/hubspot/callback/",
        EventHubSpotCallbackView.as_view(),
        name="callback",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/mapping/<int:mapping_id>/fields/",
        EventHubSpotFieldMappingView.as_view(),
        name="mapping_fields",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/sync_mapping/",
        EventHubSpotSyncMappingView.as_view(),
        name="sync_mapping",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/logs/",
        EventHubSpotLogView.as_view(),
        name="logs",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/sync-problems/",
        SyncProblemsView.as_view(),
        name="sync_problems",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/sync-problems/retry/<int:order_id>/",
        RetrySyncView.as_view(),
        name="sync_retry",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/sync-problems/retry-all/",
        RetryAllFailedView.as_view(),
        name="sync_retry_all",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/sync-problems/retry-bulk/",
        SyncRetryBulkView.as_view(),
        name="sync_retry_bulk",
    ),
    path(
        "control/event/<orgslug:organizer>/<slug:event>/hubspot/sync-problems/dismiss/<int:log_id>/",
        DismissSyncView.as_view(),
        name="sync_dismiss",
    ),
]
