# Generated by Django 5.2.14 on 2026-06-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0028_product_free_price_max_product_free_price_min_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubSpotEventSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_enabled", models.BooleanField(default=False)),
                ("sync_contacts", models.BooleanField(default=True)),
                ("sync_deals", models.BooleanField(default=True)),
                ("deal_pipeline", models.CharField(blank=True, max_length=200)),
                ("deal_stage", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="base.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "HubSpot Event Settings",
                "verbose_name_plural": "HubSpot Event Settings",
            },
        ),
        migrations.CreateModel(
            name="HubSpotOAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_type", models.CharField(default="bearer", max_length=50)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("hub_id", models.CharField(blank=True, max_length=100)),
                ("scope", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="base.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "HubSpot OAuth Token",
                "verbose_name_plural": "HubSpot OAuth Tokens",
            },
        ),
        migrations.CreateModel(
            name="HubSpotObjectMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventyay_model", models.CharField(max_length=50)),
                ("eventyay_id", models.CharField(max_length=190)),
                ("hubspot_object_type", models.CharField(max_length=50)),
                ("hubspot_object_id", models.CharField(max_length=190)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "HubSpot Object Mapping",
                "verbose_name_plural": "HubSpot Object Mappings",
                "unique_together": {
                    ("event", "eventyay_model", "eventyay_id", "hubspot_object_type")
                },
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                ("direction", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.event"
                    ),
                ),
                (
                    "object_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hubspot.hubspotobjectmapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HubSpotFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventyay_model", models.CharField(max_length=50)),
                ("eventyay_field", models.CharField(max_length=190)),
                ("hubspot_object_type", models.CharField(max_length=50)),
                ("hubspot_property", models.CharField(max_length=190)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "HubSpot Field Mapping",
                "verbose_name_plural": "HubSpot Field Mappings",
                "unique_together": {
                    ("event", "eventyay_model", "eventyay_field", "hubspot_object_type")
                },
            },
        ),
    ]
