# Generated by Django 5.2.15 on 2026-06-29 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubspot", "0004_hubspotproperty_hubspotpropertysyncstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("disconnect", "Disconnect"),
                    ("token_refresh", "Token Refresh"),
                    ("refresh_failed", "Refresh Failed"),
                    ("mapping_updated", "Mapping Updated"),
                ],
                max_length=20,
            ),
        ),
    ]
