# Generated by Django 5.2.15 on 2026-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubspot", "0004_hubspotproperty_hubspotpropertysyncstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("disconnect", "Disconnect"),
                    ("token_refresh", "Token Refresh"),
                    ("refresh_failed", "Refresh Failed"),
                    ("mapping_updated", "Mapping Updated"),
                ],
                max_length=20,
            ),
        ),
    ]
