# Generated by Django 5.2.15 on 2026-06-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubspot", "0005_hubspotfieldmapping_sync_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubspoteventsettings",
            name="auto_sync_enabled",
            field=models.BooleanField(default=True, verbose_name="Sync automatically"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("disconnect", "Disconnect"),
                    ("token_refresh", "Token Refresh"),
                    ("refresh_failed", "Refresh Failed"),
                    ("mapping_updated", "Mapping Updated"),
                    ("auto_sync_enabled", "Auto Sync Enabled"),
                    ("auto_sync_disabled", "Auto Sync Disabled"),
                ],
                max_length=20,
            ),
        ),
    ]
