# Generated by Django 5.2.15 on 2026-07-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubspot", "0006_hubspoteventsettings_auto_sync_enabled_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hubspotpropertysyncstate",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="hubspotpropertysyncstate",
            name="event",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("disconnect", "Disconnect"),
                    ("token_refresh", "Token Refresh"),
                    ("refresh_failed", "Refresh Failed"),
                    ("mapping_updated", "Mapping Updated"),
                    ("field_map_updated", "Field Mapping Updated"),
                    ("auto_sync_enabled", "Auto Sync Enabled"),
                    ("auto_sync_disabled", "Auto Sync Disabled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("connect", "Connect"),
                    ("disconnect", "Disconnect"),
                    ("token_refresh", "Token Refresh"),
                    ("refresh_failed", "Refresh Failed"),
                    ("dismiss", "Dismiss"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="HubSpotProperty",
        ),
        migrations.DeleteModel(
            name="HubSpotPropertySyncState",
        ),
    ]
