# Generated by Django 5.2.15 on 2026-07-30 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0047_team_can_manage_social_media"),
        ("hubspot", "0007_alter_hubspotpropertysyncstate_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("disconnect", "Disconnect"),
                    ("token_refresh", "Token Refresh"),
                    ("refresh_failed", "Refresh Failed"),
                    ("mapping_updated", "Mapping Updated"),
                    ("field_map_updated", "Field Mapping Updated"),
                    ("auto_sync_enabled", "Auto Sync Enabled"),
                    ("auto_sync_disabled", "Auto Sync Disabled"),
                    ("org_connect", "Org Connect"),
                    ("org_disconnect", "Org Disconnect"),
                    ("org_toggle", "Org Toggle"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrganizerHubSpotOAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_access_token", models.TextField(db_column="access_token")),
                ("_refresh_token", models.TextField(db_column="refresh_token")),
                (
                    "token_type",
                    models.CharField(
                        choices=[("bearer", "Bearer")], default="bearer", max_length=50
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("hub_id", models.CharField(blank=True, max_length=100)),
                ("hub_name", models.CharField(blank=True, max_length=200)),
                ("scope", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="base.organizer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizer HubSpot OAuth Token",
                "verbose_name_plural": "Organizer HubSpot OAuth Tokens",
            },
        ),
        migrations.CreateModel(
            name="OrganizerHubSpotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="base.organizer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizer HubSpot Settings",
                "verbose_name_plural": "Organizer HubSpot Settings",
            },
        ),
    ]
