# Generated by Django 5.2.16 on 2026-08-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0047_team_can_manage_social_media"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("hubspot", "0008_alter_auditlog_action_organizerhubspotoauthtoken_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hubspotfieldmapping",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="hubspoteventsettings",
            name="has_mapping_conflict",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hubspotfieldmapping",
            name="source",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("organizer_default", "Organizer default"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hubspotfieldmapping",
            unique_together={
                (
                    "event",
                    "content_type",
                    "eventyay_field",
                    "hubspot_object_type",
                    "source",
                )
            },
        ),
        migrations.CreateModel(
            name="OrganizerDefaultObjectTypeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eventyay_object_type",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("order_position", "Order position"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "hubspot_object_type",
                    models.CharField(
                        choices=[("contacts", "Contacts"), ("deals", "Deals")],
                        max_length=50,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.organizer"
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
                "unique_together": {
                    ("organizer", "eventyay_object_type", "hubspot_object_type")
                },
            },
        ),
        migrations.CreateModel(
            name="OrganizerDefaultFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventyay_field", models.CharField(max_length=190)),
                ("hubspot_property", models.CharField(max_length=190)),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[
                            ("identifier", "Identifier"),
                            ("overwrite", "Overwrite"),
                            ("fill_if_new", "Fill if new"),
                            ("fill_if_empty", "Fill if empty"),
                        ],
                        default="overwrite",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_type_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="hubspot.organizerdefaultobjecttypemapping",
                    ),
                ),
            ],
            options={
                "unique_together": {("object_type_mapping", "eventyay_field")},
            },
        ),
    ]
